controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Arm: Group Position Controller (type만 명시)
    arm_position_controller:
      type: position_controllers/JointGroupPositionController

    # Blade: Group Velocity Controller (type만 명시)
    blade_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Drive: diff drive
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    # Wheel test: Group Velocity Controller (type만 명시)
    wheel_test_controller:
      type: velocity_controllers/JointGroupVelocityController


# === 각 컨트롤러 개별 파라미터는 Top-level에서 ros__parameters에 명시 ===
arm_position_controller:
  ros__parameters:
    joints: ["arm_joint"]
    # JointGroupPositionController는 interface_name 필요 없음

blade_velocity_controller:
  ros__parameters:
    joints: ["blade_joint"]
    # JointGroupVelocityController도 interface_name 불필요

wheel_test_controller:
  ros__parameters:
    joints: [
      "left_wheel_1_joint", "left_wheel_2_joint", "left_wheel_3_joint",
      "right_wheel_1_joint", "right_wheel_2_joint", "right_wheel_3_joint"
      ]
